
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 7;
  public static final int TERMINATOR = 57;
  public static final int GE = 34;
  public static final int UMINUS = 29;
  public static final int SLPAR = 21;
  public static final int INT = 12;
  public static final int FOR = 17;
  public static final int MINUS = 26;
  public static final int WRITE = 48;
  public static final int BRPAR = 24;
  public static final int AND = 40;
  public static final int NOT = 39;
  public static final int SEMICOLON = 32;
  public static final int LT = 35;
  public static final int RPAR = 20;
  public static final int NIL = 9;
  public static final int NOP = 16;
  public static final int OR = 41;
  public static final int BLANK = 55;
  public static final int BOOL = 13;
  public static final int COMMA = 30;
  public static final int DIV = 28;
  public static final int FLOAT_CONST = 53;
  public static final int PLUS = 25;
  public static final int ASSIGN = 43;
  public static final int MAIN = 8;
  public static final int IF = 2;
  public static final int EXP = 54;
  public static final int ID = 44;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 50;
  public static final int INT_CONST = 51;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int GLOBAL = 49;
  public static final int SRPAR = 22;
  public static final int EQ = 37;
  public static final int TIMES = 27;
  public static final int ARROW = 15;
  public static final int COLON = 31;
  public static final int SHARP = 42;
  public static final int ELSE = 4;
  public static final int READ = 47;
  public static final int WHILE = 5;
  public static final int BLPAR = 23;
  public static final int FLOAT = 11;
  public static final int THEN = 3;
  public static final int NE = 38;
  public static final int END = 10;
  public static final int LPAR = 19;
  public static final int STRING = 14;
  public static final int LOCAL = 18;
  public static final int FALSE = 46;
  public static final int STRING_CONST = 56;
  public static final int GT = 33;
  public static final int DO = 6;
  public static final int IDENTIFIER = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FUNCTION",
  "MAIN",
  "NIL",
  "END",
  "FLOAT",
  "INT",
  "BOOL",
  "STRING",
  "ARROW",
  "NOP",
  "FOR",
  "LOCAL",
  "LPAR",
  "RPAR",
  "SLPAR",
  "SRPAR",
  "BLPAR",
  "BRPAR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "AND",
  "OR",
  "SHARP",
  "ASSIGN",
  "ID",
  "TRUE",
  "FALSE",
  "READ",
  "WRITE",
  "GLOBAL",
  "RETURN",
  "INT_CONST",
  "IDENTIFIER",
  "FLOAT_CONST",
  "EXP",
  "BLANK",
  "STRING_CONST",
  "TERMINATOR"
  };
}

